FROM node:12-alpine AS build

# Install global npm packages
#RUN npm i -g @angular/cli

# Set working directory
WORKDIR /usr/app

# Copy and install local npm packages
COPY package.json* package-lock.json* ./
RUN npm install

# Copy the remaining source code
COPY . .
EXPOSE 4200/tcp
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "500"]
