version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /data/mongodb/db:/data/db
    # ports:
    #   - 27017:27017
  client:
    environment:
      SERVER_PATH: localhost/graphql
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    volumes:
      - ./certs/:/etc/nginx/certs
  server:
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_URL: ${DB_URL}
    build: ./backend
    depends_on:
      - mongodb