version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
  client:
    environment:
      SERVER_PATH: localhost:4000/graphql
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
  server:
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_URL: ${DB_URL}
    build: ./backend
    # volumes:
    #   - /usr/app/node_modules
    #   - ./frontend:/usr/app
    depends_on:
      - mongodb
    ports:
      - 3000:3000
      - 4000:4000