version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ideazboard
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
  server:
    build: .
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    depends_on:
      - mongodb
    ports:
      - 3000:3000
      - 4000:4000
secrets:                        # top level secrets block
  my_file_secret:
    file: my_file_secret.txt